### ISSUE TITLE
Error using max_planck.obj 

### ISSUE THREAD

**Issue by wangmiaowei** [threedle/TextDeformer#1]
I do not know whether you meet this problem when replacing shape with max_planck.obj in the YAML file.
<img width="748" alt="企业微信截图_0005e43d-9d6c-4188-8c0b-bb14e511406e" src="https://user-images.githubusercontent.com/27915265/236407594-223cd831-a19e-4784-b0d7-664762f157ce.png">

**Comment by wangmiaowei** [comment]
Well, I now this reason. Your mesh does not provide the material file. But when I use my mesh with mtl file, then another error happens:
<img width="862" alt="企业微信截图_d01d1512-076d-43c2-af6c-256c3954972c" src="https://user-images.githubusercontent.com/27915265/236409410-1789e2f8-a5e1-403f-b3c5-69303c4b7f33.png">

**Comment by wangmiaowei** [comment]
Besides, even if I do not change the shape, only modify the text prompt: I also get another error:
<img width="853" alt="企业微信截图_b6a27867-6274-43b9-831c-984022ab2688" src="https://user-images.githubusercontent.com/27915265/236410866-b1699980-ae0a-4f6a-aa7b-f747a715e629.png">

**Comment by ChocolateBiscuit** [comment]
I do not run into this issue when running with `max_planck.obj`. The error is saying that the mesh has no texture coordinates -- I am not sure how this is possible since [this line of code](https://github.com/threedle/TextDeformer/blob/main/loop.py#L83) computes a trivial parameterization for any mesh which does not have texture coordinates. Can you share your config file and command that you are running?

For the second error, this could be a variety of issues -- for example, the Neural Jacobian Fields code does not work for meshes that have more than one connected component. I can take a look if you share your mesh file.

**Comment by wangmiaowei** [comment]
Thanks for your help. For the first question, I modified that code line(version) to be adapted to my machine. There is a bug here and looks good now. For the second question, I upload my test mesh(.zip) here. From your current expression, it seems a converting tool to your requirement is necessary if want to have a broad application. 
[musk_mesh.zip](https://github.com/threedle/TextDeformer/files/11405647/musk_mesh.zip)

**Comment by ChocolateBiscuit** [comment]
I took a look at your mesh, first there seems to be a box surrounding the face.
![image](https://user-images.githubusercontent.com/20386814/236596082-21e73dd3-3272-405e-97c6-63909a706ba8.png)
Aside from that, the mesh consists of nearly 2000 connected components. While our code _can_ be extended to multiple connected components (you may parameterize each mesh with Jacobians and also learn a global translation for each shape to position them), it was not written to handle this case, where the thousands of components are intended to be one single object. One suggestion is to try to merge the components and re-mesh in blender.

**Comment by wangmiaowei** [comment]
Thanks for your reply. You can try to use this mesh( no bounding box here). It still gets  Matrix is not positive definite!
[muskD.obj.zip](https://github.com/threedle/TextDeformer/files/11411252/muskD.obj.zip)

**Comment by ethanhe42** [comment]
Any idea how to convert the object? 

my conversion script doesn't work:
```
import bpy

# Load the .obj file
bpy.ops.import_scene.obj(filepath="input.obj")
bpy.ops.object.select_all(action='SELECT')

# Get the active object
obj = bpy.context.selected_objects[0]

# Merge components
bpy.ops.object.mode_set(mode='EDIT')
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.remove_doubles()
bpy.ops.object.mode_set(mode='OBJECT')

# Re-mesh
bpy.ops.object.modifier_add(type='REMESH')
bpy.context.object.modifiers["Remesh"].octree_depth = 6
bpy.ops.object.modifier_apply(modifier="Remesh")

# Export the new .obj file
bpy.ops.export_scene.obj(filepath="output.obj", use_selection=True)
```
