### ISSUE TITLE
fatal error: EGL/egl.h: No such file or directory

### ISSUE THREAD

**Issue by weiyao1996** [threedle/TextDeformer#4]
Hi,

Thanks for sharing your really nice work!
When I run main.py, I met this error related to nvdiffrast. Please let me know if you have any ideas to address this problem. Many thanks.

**Comment by ChocolateBiscuit** [comment]
Hi,

This seems to be an issue in setting up nvdiffrast. Here is a similar issue: https://github.com/NVlabs/nvdiffrast/issues/56. I would recommend taking a look at their [docker file](https://github.com/NVlabs/nvdiffrast/blob/main/docker/Dockerfile) and checking if you're missing any required packages.

**Comment by kamwoh** [comment]
i faced this error too, solved it with `sudo apt-get install libegl1-mesa-dev`

**Comment by weiyao1996** [comment]
Thank you very much!
