### ISSUE TITLE
Question on parameters for human faces

### ISSUE THREAD

**Issue by nsarafianos** [threedle/TextDeformer#5]
Thanks for your great work and for putting this nice code together! 

I have a question regarding finding proper parameters in the .yml. When I'm trying to go from Max Planck to Einstein/Obama the results I obtain are not as smooth as what's shown in the paper but instead the output has rough edges (providing one example below where batch_size = 50, epochs=3500, train_res=512, lr=0.005). I'm wondering what's the trick that I'm missing and whether it's a matter of parameters or different desciptions ("bust of Albert Einstein" vs "Einstein" for example). Happy to get your insights! 

Thanks again! 

![image](https://github.com/threedle/TextDeformer/assets/14354430/1f3db866-caf1-4929-9611-37e511d275aa)

**Comment by ChocolateBiscuit** [comment]
Thanks for your interest in our work!

There's no cure-all trick unfortunately, you will probably have to play around with the hyper-parameters and text prompts. I can tell you that all of the paper experiments were run with ``batch_size=25`` and ``lr=0.0025``. Generally, 2500 epochs is enough as well, although this can vary a bit (you may get more dramatic deformations running for longer). Definitely try different variations of the text prompt, I think "a bust of Albert Einstein" should work.

**Comment by nsarafianos** [comment]
Thank you!
