### ISSUE TITLE
CholeskySolverD: Matrix is not positive definite

### ISSUE THREAD

**Issue by nsarafianos** [threedle/TextDeformer#6]
Thanks for this great codebase. One quick question: 

Given some new triangle meshes as input, CholeskySolverD returns an error that the matrix is not positive definite. Did you encounter this at any point and if so do you know how to fix it? I've already double-checked that the  normals are properly oriented. 

Thanks!

**Comment by ChocolateBiscuit** [comment]
We did encounter this at some points, the most likely culprit in my experience is that the input mesh is not one connected component. While it is not too difficult to extend our method to multiple components (parametrize each component and render them together in the scene), our code does not handle this case.
